name: grpc-client
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - jsonpickle=2.0.0
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.3
  - openssl=1.1.1n
  - pip=21.2.4
  - pydantic=1.9.0
  - python=3.9.12
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.38.2
  - tk=8.6.11
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zipp=3.7.0
  - zlib=1.2.12
  - pip:
    - grpcio==1.44.0
    - protobuf==3.20.1
    - six==1.16.0
